// auth.js

require('dotenv').config();
const jwt = require("jsonwebtoken");

// Use the secret from .env, with a fallback
const secret = process.env.JWT_SECRET || "FallbackSecret";

// The rest of your auth.js file remains the same...
// module.exports.createAccessToken = ...
// module.exports.verify = ...
// module.exports.verifyAdmin = ...